### PR TITLE
Fix assignment of stale containers. Fixes #803

### LINKED ISSUE #803: Containers Confirm Navigation for site null
When I try to set a website to always open in a container, after hitting "open in container" to set a site to always open in a container, it then asks "You asked Firefox to always open for this site: null" in an endless loop. 
untitled

**Steps to Reproduce:** 

1. Open new container
2. Visit website
3. Right-click and select "always open in this container"
4. Click either "open in current container" or "open in container."

> About:support: 
> {
>   "application": {
>     "name": "Firefox",
>     "osVersion": "Windows_NT 10.0",
>     "version": "57.0a1",
>     "buildID": "20170908220146",
>     "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0",
>     "safeMode": false,
>     "updateChannel": "nightly",
>     "supportURL": "https://support.mozilla.org/1/firefox/57.0a1/WINNT/en-US/",
>     "numTotalWindows": 1,
>     "numRemoteWindows": 0,
>     "remoteAutoStart": false,
>     "currentContentProcesses": 1,
>     "maxContentProcesses": 4,
>     "autoStartStatus": 2,
>     "styloBuild": true,
>     "styloDefault": true,
>     "styloResult": true,
>     "keyGoogleFound": true,
>     "keyMozillaFound": true
>   },
>   "modifiedPreferences": {
>     "accessibility.typeaheadfind.flashBar": 0,
>     "browser.cache.disk.filesystem_reported": 1,
>     "browser.cache.disk.hashstats_reported": 1,
>     "browser.cache.disk.smart_size.first_run": false,
>     "browser.cache.frecency_experiment": 1,
>     "browser.cache.disk.capacity": 358400,
>     "browser.download.folderList": 0,
>     "browser.download.manager.alertOnEXEOpen": false,
>     "browser.link.open_newwindow.override.external": 3,
>     "browser.link.open_newwindow.restriction": 0,
>     "browser.places.smartBookmarksVersion": 8,
>     "browser.sessionstore.upgradeBackup.latestBuildID": "20170908220146",
>     "browser.startup.homepage_override.mstone": "57.0a1",
>     "browser.startup.homepage": "http://www.ighome.com/",
>     "browser.startup.homepage_override.buildID": "20170908220146",
>     "browser.tabs.remote.autostart.2": false,
>     "browser.tabs.crashReporting.includeURL": true,
>     "browser.urlbar.lastSuggestionsPromptDate": 20170524,
>     "browser.urlbar.timesBeforeHidingSuggestionsHint": 0,
>     "browser.urlbar.maxRichResults": 12,
>     "browser.urlbar.usepreloadedtopurls.enabled": false,
>     "browser.urlbar.searchSuggestionsChoice": true,
>     "dom.push.userAgentID": "9115ca0ebfdd443f9a1872ddee24df4c",
>     "dom.event.clipboardevents.enabled": false,
>     "dom.forms.autocomplete.formautofill": true,
>     "extensions.lastAppVersion": "57.0a1",
>     "font.size.variable.x-western": 14,
>     "font.internaluseonly.changed": false,
>     "layers.mlgpu.sanity-test-failed": false,
>     "media.webrtc.debug.log_file": "C:\\Users\\jesse\\AppData\\Local\\Temp\\WebRTC.log",
>     "media.gmp-widevinecdm.lastUpdate": 1504229944,
>     "media.gmp-gmpopenh264.lastUpdate": 1493915977,
>     "media.hardware-video-decoding.failed": false,
>     "media.gmp-widevinecdm.version": "1.4.8.1008",
>     "media.gmp-gmpopenh264.abi": "x86_64-msvc-x64",
>     "media.gmp-manager.lastCheck": 1504929514,
>     "media.gmp-widevinecdm.abi": "x86_64-msvc-x64",
>     "media.benchmark.vp9.versioncheck": 2,
>     "media.gmp.storage.version.observed": 1,
>     "media.benchmark.vp9.fps": 118,
>     "media.gmp-gmpopenh264.version": "1.6",
>     "media.gmp-manager.buildID": "20170908220146",
>     "network.prefetch-next": false,
>     "network.dns.disablePrefetch": true,
>     "network.http.speculative-parallel-limit": 0,
>     "network.predictor.enabled": false,
>     "network.predictor.cleaned-up": true,
>     "network.cookie.prefsMigrated": true,
>     "places.history.expiration.transient_current_max_pages": 134433,
>     "places.database.lastMaintenance": 1504875588,
>     "plugin.disable_full_page_plugin_for_types": "application/pdf",
>     "print.printer_Foxit_Reader_PDF_Printer.print_unwriteable_margin_left": 0,
>     "print.printer_Canon_MG2500_series.print_unwriteable_margin_bottom": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_headercenter": "",
>     "print.printer_Foxit_Reader_PDF_Printer.print_to_file": false,
>     "print.printer_Foxit_Reader_PDF_Printer.print_page_delay": 50,
>     "print.printer_Foxit_Reader_PDF_Printer.print_evenpages": true,
>     "print.printer_Canon_MG2500_series.print_unwriteable_margin_top": 0,
>     "print.printer_Canon_MG2500_series.print_unwriteable_margin_left": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_edge_left": 0,
>     "print.printer_Canon_MG2500_series.print_headercenter": "",
>     "print.printer_Foxit_Reader_PDF_Printer.print_reversed": false,
>     "print.printer_Foxit_Reader_PDF_Printer.print_paper_name": "",
>     "print.printer_Foxit_Reader_PDF_Printer.print_margin_bottom": "0.5",
>     "print.printer_Canon_MG2500_series.print_headerleft": "&T",
>     "print.printer_Canon_MG2500_series.print_to_file": false,
>     "print.printer_Foxit_Reader_PDF_Printer.print_footerright": "&D",
>     "print.printer_Foxit_Reader_PDF_Printer.print_edge_right": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_edge_top": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_footerleft": "&PT",
>     "print.printer_Foxit_Reader_PDF_Printer.print_unwriteable_margin_top": 0,
>     "print.printer_Canon_MG2500_series.print_margin_bottom": "0.5",
>     "print.printer_Foxit_Reader_PDF_Printer.print_shrink_to_fit": true,
>     "print.printer_Canon_MG2500_series.print_scaling": "  1.00",
>     "print.printer_Foxit_Reader_PDF_Printer.print_headerright": "&U",
>     "print.printer_Canon_MG2500_series.print_margin_left": "0.5",
>     "print.printer_Canon_MG2500_series.print_shrink_to_fit": true,
>     "print.printer_Foxit_Reader_PDF_Printer.print_oddpages": true,
>     "print.printer_Canon_MG2500_series.print_bgcolor": false,
>     "print.printer_Canon_MG2500_series.print_unwriteable_margin_right": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_in_color": true,
>     "print.printer_Canon_MG2500_series.print_footerright": "&D",
>     "print.printer_Canon_MG2500_series.print_evenpages": true,
>     "print.printer_Canon_MG2500_series.print_margin_top": "0.5",
>     "print.printer_Foxit_Reader_PDF_Printer.print_headerleft": "&T",
>     "print.printer_Canon_MG2500_series.print_reversed": false,
>     "print.printer_Canon_MG2500_series.print_oddpages": true,
>     "print.printer_Canon_MG2500_series.print_edge_bottom": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_paper_width": "  8.50",
>     "print.printer_Canon_MG2500_series.print_footerleft": "&PT",
>     "print.printer_Canon_MG2500_series.print_edge_right": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_bgcolor": false,
>     "print.printer_Foxit_Reader_PDF_Printer.print_footercenter": "",
>     "print.printer_Canon_MG2500_series.print_bgimages": false,
>     "print.printer_Canon_MG2500_series.print_paper_size_unit": 0,
>     "print.printer_Canon_MG2500_series.print_page_delay": 50,
>     "print.printer_Foxit_Reader_PDF_Printer.print_unwriteable_margin_bottom": 0,
>     "print.printer_Canon_MG2500_series.print_paper_data": 1,
>     "print.printer_Foxit_Reader_PDF_Printer.print_paper_height": " 11.00",
>     "print.printer_Foxit_Reader_PDF_Printer.print_paper_size_unit": 0,
>     "print.printer_Canon_MG2500_series.print_margin_right": "0.5",
>     "print.printer_Foxit_Reader_PDF_Printer.print_resolution": 300,
>     "print.printer_Foxit_Reader_PDF_Printer.print_duplex": -437918235,
>     "print.printer_Foxit_Reader_PDF_Printer.print_bgimages": false,
>     "print.printer_Canon_MG2500_series.print_in_color": true,
>     "print.printer_Canon_MG2500_series.print_footercenter": "",
>     "print.printer_Canon_MG2500_series.print_orientation": 0,
>     "print.printer_Canon_MG2500_series.print_paper_height": " -1.00",
>     "print.printer_Foxit_Reader_PDF_Printer.print_edge_bottom": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_paper_data": 256,
>     "print.printer_Canon_MG2500_series.print_headerright": "&U",
>     "print.printer_Canon_MG2500_series.print_paper_name": "",
>     "print.printer_Foxit_Reader_PDF_Printer.print_margin_left": "0.5",
>     "print.printer_Foxit_Reader_PDF_Printer.print_margin_top": "0.5",
>     "print.printer_Foxit_Reader_PDF_Printer.print_unwriteable_margin_right": 0,
>     "print.printer_Canon_MG2500_series.print_edge_top": 0,
>     "print.printer_Foxit_Reader_PDF_Printer.print_scaling": "  1.00",
>     "print.printer_Canon_MG2500_series.print_resolution": 600,
>     "print.printer_Canon_MG2500_series.print_paper_width": " -1.00",
>     "print.printer_Foxit_Reader_PDF_Printer.print_margin_right": "0.5",
>     "print.printer_Foxit_Reader_PDF_Printer.print_orientation": 0,
>     "print.printer_Canon_MG2500_series.print_duplex": -437918235,
>     "print.printer_Canon_MG2500_series.print_edge_left": 0,
>     "security.sandbox.content.tempDirSuffix": "{570d44b9-4b51-4e66-a63f-e2730b04dd84}",
>     "services.sync.declinedEngines": "tabs,addons",
>     "services.sync.lastPing": 1504916840,
>     "services.sync.lastSync": "Sat Sep 09 2017 07:40:05 GMT-0500 (Central Standard Time)",
>     "services.sync.engine.tabs": false,
>     "services.sync.engine.greasemonkey": true,
>     "services.sync.engine.bookmarks.validation.lastTime": 1504922119,
>     "services.sync.engine.addresses.available": true,
>     "services.sync.engine.addons": false,
>     "services.sync.engine.prefs.modified": false,
>     "storage.vacuum.last.places.sqlite": 1504022140,
>     "storage.vacuum.last.index": 1,
>     "ui.osk.debug.keyboardDisplayReason": "IKPOS: Touch screen not found."
>   },
>   "lockedPreferences": {},
>   "media": {
>     "currentAudioBackend": "wasapi",
>     "currentMaxAudioChannels": 2,
>     "currentPreferredChannelLayout": "stereo",
>     "currentPreferredSampleRate": 48000,
>     "audioOutputDevices": [
>       {
>         "name": "Speakers (Yeti Stereo Microphone)",
>         "groupId": "USB\\VID_B58E&PID_9E84&MI_00\\7&78cc2bf&0&0000",
>         "vendor": "",
>         "type": 2,
>         "state": 0,
>         "preferred": 0,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 48000,
>         "maxRate": 48000,
>         "minRate": 48000,
>         "maxLatency": 0,
>         "minLatency": 0
>       },
>       {
>         "name": "Philips FTV (Intel(R) Display Audio)",
>         "groupId": "HDAUDIO\\FUNC_01&VEN_8086&DEV_2807&SUBSYS_80860101&REV_1000\\4&1eb2714b&1&0001",
>         "vendor": "",
>         "type": 2,
>         "state": 0,
>         "preferred": 0,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 48000,
>         "maxRate": 48000,
>         "minRate": 48000,
>         "maxLatency": 0,
>         "minLatency": 0
>       },
>       {
>         "name": "Speakers / Headphones (Realtek High Definition Audio)",
>         "groupId": "HDAUDIO\\FUNC_01&VEN_10EC&DEV_0292&SUBSYS_102805BE&REV_1000\\4&1a9f60bb&1&0001",
>         "vendor": "",
>         "type": 2,
>         "state": 2,
>         "preferred": 7,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 48000,
>         "maxRate": 48000,
>         "minRate": 48000,
>         "maxLatency": 480,
>         "minLatency": 144
>       }
>     ],
>     "audioInputDevices": [
>       {
>         "name": "Jack Mic (Realtek High Definition Audio)",
>         "groupId": "HDAUDIO\\FUNC_01&VEN_10EC&DEV_0292&SUBSYS_102805BE&REV_1000\\4&1a9f60bb&1&0001",
>         "vendor": "",
>         "type": 1,
>         "state": 1,
>         "preferred": 0,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 48000,
>         "maxRate": 48000,
>         "minRate": 48000,
>         "maxLatency": 0,
>         "minLatency": 0
>       },
>       {
>         "name": "Microphone (Yeti Stereo Microphone)",
>         "groupId": "USB\\VID_B58E&PID_9E84&MI_00\\7&78cc2bf&0&0000",
>         "vendor": "",
>         "type": 1,
>         "state": 0,
>         "preferred": 0,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 44100,
>         "maxRate": 44100,
>         "minRate": 44100,
>         "maxLatency": 0,
>         "minLatency": 0
>       },
>       {
>         "name": "Stereo Mix (Realtek High Definition Audio)",
>         "groupId": "HDAUDIO\\FUNC_01&VEN_10EC&DEV_0292&SUBSYS_102805BE&REV_1000\\4&1a9f60bb&1&0001",
>         "vendor": "",
>         "type": 1,
>         "state": 0,
>         "preferred": 0,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 48000,
>         "maxRate": 48000,
>         "minRate": 48000,
>         "maxLatency": 0,
>         "minLatency": 0
>       },
>       {
>         "name": "Microphone Array (Realtek High Definition Audio)",
>         "groupId": "HDAUDIO\\FUNC_01&VEN_10EC&DEV_0292&SUBSYS_102805BE&REV_1000\\4&1a9f60bb&1&0001",
>         "vendor": "",
>         "type": 1,
>         "state": 2,
>         "preferred": 7,
>         "supportedFormat": 4112,
>         "defaultFormat": 4096,
>         "maxChannels": 2,
>         "defaultRate": 48000,
>         "maxRate": 48000,
>         "minRate": 48000,
>         "maxLatency": 480,
>         "minLatency": 144
>       }
>     ]
>   },
>   "javaScript": {
>     "incrementalGCEnabled": true
>   },
>   "accessibility": {
>     "isActive": false,
>     "forceDisabled": 0,
>     "handlerUsed": true,
>     "instantiator": ""
>   },
>   "libraryVersions": {
>     "NSPR": {
>       "minVersion": "4.17 Beta",
>       "version": "4.17 Beta"
>     },
>     "NSS": {
>       "minVersion": "3.33 Beta",
>       "version": "3.33 Beta"
>     },
>     "NSSUTIL": {
>       "minVersion": "3.33 Beta",
>       "version": "3.33 Beta"
>     },
>     "NSSSSL": {
>       "minVersion": "3.33 Beta",
>       "version": "3.33 Beta"
>     },
>     "NSSSMIME": {
>       "minVersion": "3.33 Beta",
>       "version": "3.33 Beta"
>     }
>   },
>   "userJS": {
>     "exists": false
>   },
>   "crashes": {
>     "submitted": [],
>     "pending": 0
>   },
>   "sandbox": {
>     "contentSandboxLevel": 4,
>     "effectiveContentSandboxLevel": 4
>   },
>   "graphics": {
>     "numTotalWindows": 1,
>     "numAcceleratedWindows": 1,
>     "windowLayerManagerType": "Direct3D 11",
>     "windowLayerManagerRemote": true,
>     "windowUsingAdvancedLayers": true,
>     "adapterDescription": "Intel(R) HD Graphics 4600",
>     "adapterVendorID": "0x8086",
>     "adapterDeviceID": "0x0416",
>     "adapterSubsysID": "05be1028",
>     "adapterRAM": "Unknown",
>     "adapterDrivers": "igdumdim64 igd10iumd64 igd10iumd64 igd12umd64 igdumdim32 igd10iumd32 igd10iumd32 igd12umd32",
>     "driverVersion": "20.19.15.4531",
>     "driverDate": "9-29-2016",
>     "adapterDescription2": "",
>     "adapterVendorID2": "",
>     "adapterDeviceID2": "",
>     "adapterSubsysID2": "",
>     "adapterRAM2": "",
>     "adapterDrivers2": "",
>     "driverVersion2": "",
>     "driverDate2": "",
>     "isGPU2Active": false,
>     "direct2DEnabled": true,
>     "directWriteEnabled": true,
>     "directWriteVersion": "10.0.16278.1000",
>     "clearTypeParameters": "Gamma: 2.2 Pixel Structure: RGB ClearType Level: 100 Enhanced Contrast: 400 ",
>     "offMainThreadPaintEnabled": false,
>     "webgl1Renderer": "Google Inc. -- ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)",
>     "webgl1Version": "OpenGL ES 2.0 (ANGLE 2.1.0.dec065540d5f)",
>     "webgl1DriverExtensions": "GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object ",
>     "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture",
>     "webgl1WSIInfo": "EGL_VENDOR: Google Inc. (adapter LUID: 000000000000942e)\nEGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f)\nEGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture_nv12 EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource \nEGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses ",
>     "webgl2Renderer": "Google Inc. -- ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)",
>     "webgl2Version": "OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)",
>     "webgl2DriverExtensions": "GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object ",
>     "webgl2Extensions": "EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc",
>     "webgl2WSIInfo": "EGL_VENDOR: Google Inc. (adapter LUID: 000000000000942e)\nEGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f)\nEGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture_nv12 EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource \nEGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses ",
>     "info": {
>       "AzureCanvasBackend": "direct2d 1.1",
>       "AzureFallbackCanvasBackend": "skia",
>       "AzureContentBackend": "direct2d 1.1",
>       "AzureCanvasAccelerated": 0
>     },
>     "featureLog": {
>       "features": [
>         {
>           "name": "HW_COMPOSITING",
>           "description": "Compositing",
>           "status": "available",
>           "log": [
>             {
>               "type": "default",
>               "status": "available"
>             }
>           ]
>         },
>         {
>           "name": "D3D11_COMPOSITING",
>           "description": "Direct3D11 Compositing",
>           "status": "available",
>           "log": [
>             {
>               "type": "default",
>               "status": "available"
>             }
>           ]
>         },
>         {
>           "name": "DIRECT2D",
>           "description": "Direct2D",
>           "status": "available",
>           "log": [
>             {
>               "type": "default",
>               "status": "available"
>             }
>           ]
>         },
>         {
>           "name": "D3D11_HW_ANGLE",
>           "description": "Direct3D11 hardware ANGLE",
>           "status": "available",
>           "log": [
>             {
>               "type": "default",
>               "status": "available"
>             }
>           ]
>         },
>         {
>           "name": "GPU_PROCESS",
>           "description": "GPU Process",
>           "status": "unavailable",
>           "log": [
>             {
>               "type": "default",
>               "status": "unavailable",
>               "message": "Multi-process mode is not enabled"
>             }
>           ]
>         },
>         {
>           "name": "WEBRENDER",
>           "description": "WebRender",
>           "status": "unavailable",
>           "log": [
>             {
>               "type": "default",
>               "status": "opt-in",
>               "message": "WebRender is an opt-in feature"
>             },
>             {
>               "type": "runtime",
>               "status": "unavailable",
>               "message": "GPU Process is disabled"
>             }
>           ]
>         },
>         {
>           "name": "ADVANCED_LAYERS",
>           "description": "Advanced Layers",
>           "status": "available",
>           "log": [
>             {
>               "type": "default",
>               "status": "available"
>             }
>           ]
>         }
>       ],
>       "fallbacks": []
>     },
>     "crashGuards": []
>   },
>   "experiments": [
>     {
>       "id": "unaccelerated-compositor-process-nightly56@experiments.mozilla.org",
>       "name": "Unaccelerated Compositor Process Nightly 56",
>       "description": "Measures the impact of enabling compositor process for users without hardware acceleration in Firefox Nightly 56 on Windows",
>       "active": false,
>       "endDate": 1501252466264,
>       "detailURL": "",
>       "branch": "disqualified"
>     }
>   ],
>   "extensions": [
>     {
>       "name": "Beyond Australis",
>       "version": "1.4.8",
>       "isActive": true,
>       "id": "thefoxonlybetter@quicksaver"
>     },
>     {
>       "name": "Download Status Bar",
>       "version": "15.0.0.1",
>       "isActive": true,
>       "id": "{6c28e999-e900-4635-a39d-b1ec90ba0c0f}"
>     },
>     {
>       "name": "Forecastfox (fix version)",
>       "version": "4.8",
>       "isActive": true,
>       "id": "forecastfox@s3_fix_version"
>     },
>     {
>       "name": "Greasemonkey",
>       "version": "3.11",
>       "isActive": true,
>       "id": "{e4a8a97b-f2ed-450b-b12d-ee082ba24781}"
>     },
>     {
>       "name": "Messenger for Google™ Hangouts",
>       "version": "0.1.9",
>       "isActive": true,
>       "id": "jid1-uqbSKwXpf2K6yl@jetpack"
>     },
>     {
>       "name": "New Add-on Bar",
>       "version": "0.24",
>       "isActive": true,
>       "id": "ausaddonbar@teo.pl"
>     },
>     {
>       "name": "Night Mode Pro",
>       "version": "0.2.1",
>       "isActive": true,
>       "id": "jid1-w2rQFrS7t0PHJo@jetpack"
>     },
>     {
>       "name": "Nightly Tester Tools",
>       "version": "3.10",
>       "isActive": true,
>       "id": "{8620c15f-30dc-4dba-a131-7c5d20cf4a29}"
>     },
>     {
>       "name": "Open in IE",
>       "version": "1.5.0.1-signed",
>       "isActive": true,
>       "id": "openinie@wittersworld.com"
>     },
>     {
>       "name": "passLikeW8",
>       "version": "0.2.1-signed.1-signed",
>       "isActive": true,
>       "id": "jid1-BQiF0h2eHzXeZQ@jetpack"
>     },
>     {
>       "name": "Private Tab",
>       "version": "0.2.2",
>       "isActive": true,
>       "id": "privateTab@infocatcher"
>     },
>     {
>       "name": "RECAP",
>       "version": "0.9.2.2.1-signed.1-signed",
>       "isActive": true,
>       "id": "info@recapthelaw.org"
>     },
>     {
>       "name": "Slim Add-ons Manager",
>       "version": "14.1",
>       "isActive": true,
>       "id": "slimaddonmanager@opendfki.de"
>     },
>     {
>       "name": "Test Pilot",
>       "version": "2.0.2-dev-1c11ce2",
>       "isActive": true,
>       "id": "@testpilot-addon"
>     },
>     {
>       "name": "Testpilot containers",
>       "version": "3.1.0",
>       "isActive": true,
>       "id": "@testpilot-containers"
>     },
>     {
>       "name": "uBlock Origin",
>       "version": "1.14.9b0",
>       "isActive": true,
>       "id": "uBlock0@raymondhill.net"
>     },
>     {
>       "name": "Unhide Passwords",
>       "version": "1.2.7.0.1-signed.1-signed",
>       "isActive": true,
>       "id": "{2e17e2b2-b8d4-4a67-8d7b-fafa6cc9d1d0}"
>     },
>     {
>       "name": "Video DownloadHelper",
>       "version": "6.3.1",
>       "isActive": true,
>       "id": "{b9db16a4-6edc-47ec-a1f4-b86292ed211d}"
>     }
>   ],
>   "features": [
>     {
>       "name": "Activity Stream",
>       "version": "2017.09.08.0882-3dbf720c",
>       "id": "activity-stream@mozilla.org"
>     },
>     {
>       "name": "Application Update Service Helper",
>       "version": "2.0",
>       "id": "aushelper@mozilla.org"
>     },
>     {
>       "name": "Click-to-Play staged rollout",
>       "version": "1.2",
>       "id": "clicktoplay-rollout@mozilla.org"
>     },
>     {
>       "name": "Firefox Screenshots",
>       "version": "16.1.0",
>       "id": "screenshots@mozilla.org"
>     },
>     {
>       "name": "FlyWeb",
>       "version": "1.0.0",
>       "id": "flyweb@mozilla.org"
>     },
>     {
>       "name": "Follow-on Search Telemetry",
>       "version": "0.9.3",
>       "id": "followonsearch@mozilla.com"
>     },
>     {
>       "name": "Form Autofill",
>       "version": "1.0",
>       "id": "formautofill@mozilla.org"
>     },
>     {
>       "name": "Multi-process staged rollout",
>       "version": "3.00",
>       "id": "e10srollout@mozilla.org"
>     },
>     {
>       "name": "Photon onboarding",
>       "version": "0.1",
>       "id": "onboarding@mozilla.org"
>     },
>     {
>       "name": "Pocket",
>       "version": "1.0.5",
>       "id": "firefox@getpocket.com"
>     },
>     {
>       "name": "Presentation",
>       "version": "1.0.0",
>       "id": "presentation@mozilla.org"
>     },
>     {
>       "name": "Shield Recipe Client",
>       "version": "73",
>       "id": "shield-recipe-client@mozilla.org"
>     },
>     {
>       "name": "Web Compat",
>       "version": "1.1",
>       "id": "webcompat@mozilla.org"
>     },
>     {
>       "name": "WebCompat Reporter",
>       "version": "1.0.0",
>       "id": "webcompat-reporter@mozilla.org"
>     }
>   ]
> }

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

File: webextension/js/background/assignManager.js [hunk 1]
```diff
@@ -113,54 +113,69 @@ const assignManager = {
...
-        */
-        if (backgroundLogic.NEW_TAB_PAGES.has(tab.url)
-            || (messageHandler.lastCreatedTab
-            && messageHandler.lastCreatedTab.id === tab.id)) {
-          browser.tabs.remove(tab.id);
-        }
-        return {
-          cancel: true,
-        };
-      }).catch((e) => {
```
Comment (groovecoder) [inline webextension/js/background/assignManager.js]: Weird ... I don't see the corresponding `try` statement for this?
