### PR TITLE
remove HTML entities from tooltip

### LINKED ISSUE #1507: Tooltip shows HTML entities for some characters
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Windows 10 1809
- Firefox Version: 69.0.1, 70.0b9 (dev edition)
- Other installed Add-ons + Version + Enabled/Disabled-Status: none in dev edition

### Actual behavior
The tooltip on containers in the container list displays HTML entities for some characters, for example, container `a/b c` has the tooltip `a&#x2F;b c`

Screenshots:

image

image

### Expected behavior
The tooltip should display the same text as in the container list

### Steps to reproduce
1. Create container with special characters like `&` or `/`
2. Open Multi-Account-Container addon dropdown from Firefox toolbar
3. Hover mouse on a container

### PR DESCRIPTION
**Pull request by Jo-IE**
#outreachy applicant fixes #1507 

@maxxcrawford @groovecoder this PR closes #1507 and any feedback will be greatly appreciated! 

I had all tests (run using `npm test`) passing locally.

### CODE REVIEW

File: src/js/popup.js [hunk 1]
```diff
@@ -637,9 +637,9 @@ Logic.registerPanel(P_CONTAINERS_LIST, {
 
       context.classList.add("userContext-wrapper", "open-newtab", "clickable");
       manage.classList.add("show-tabs", "pop-button");
-      manage.title = escaped`View ${identity.name} container`;
+      manage.setAttribute("title", `View ${identity.name} container`);
       context.setAttribute("tabindex", "0");
-      context.title = escaped`Create ${identity.name} tab`;
+      context.setAttribute("title", `Create ${identity.name} tab`);
```
Comment (groovecoder) [inline src/js/popup.js]: Nice. This still avoids the self-XSS potential too.
image
